### ISSUE TITLE
jftui fails to start if $XDG_CONFIG_HOME/jftui does not exist

### ISSUE THREAD

**Issue by p-rintz** [Aanok/jftui#1]
Hi there,
when using jftui for the first time, it will ask for configuration. Once done, it will fail with the following message if the config folder does not already exist:
Warning: jf_config_write: fopen: No such file or directory

Once I create $XDG_CONFIG_HOME/jftui manually and rerun the configuration, jftui starts fine.

**Comment by Aanok** [comment]
Thanks for the report! There are a few other fixes I want to add, then I'll package a new release :)
