### ISSUE TITLE
"Native Mode" Ability to access local files through 'Shared Network Folders'

### ISSUE THREAD

**Issue by rdrr** [Aanok/jftui#10]
Would love if jftui could support something similar to the Kodi native mode where files are accessed directly from the file server.

I currently use jftui to sync my progress across all my media devices.  This way Jellyfin is the one true source.  However using it now, the file is being read from my desktop through to the Jellyfin server to be played back on my desktop.  Seeking and other features are degraded.

Thank you for the consideration.

**Comment by Aanok** [comment]
Good point! It's strongly suggested to do that on the old Emby development docs too, in fact.

**Comment by Aanok** [comment]
Hey @rdrr ! This, err... took a while, but we got there! It's implemented now as of v0.6.0 :)

**Comment by rdrr** [comment]
@Aanok Wow, awesome!  Thanks! Great work!
