### ISSUE TITLE
Feature request: remote player support

### ISSUE THREAD

**Issue by Maxr1998** [Aanok/jftui#13]
When using the Jellyfin webplayer, one can use other devices to remote control the current playback. As far as I understand it, it uses the WebSocket API to register a session, and receive the playback commands. There's documentation of this API on the [Emby wiki](https://github.com/MediaBrowser/Emby/wiki/Web-Socket).
It'd be nice if jftui could support this feature.

For the websocket implementation, [LWS](https://libwebsockets.org/) seems to be a nice library. libcurl might support those with some tweaking as well, don't know what'd be preferable here.

**Comment by Aanok** [comment]
I don't think this should be within the scope of jftui, generally speaking.

You'll want to look into the [mpv-shim](https://github.com/iwalton3/jellyfin-mpv-shim) client: it's exactly what you're asking for :)

**Comment by Maxr1998** [comment]
Huh, neat. Didn't know that existed. Thanks!
