### ISSUE TITLE
Jellyfin 10.7.0 breaks jftui menus

### ISSUE THREAD

**Issue by Aanok** [Aanok/jftui#18]
**jftui version**
latest

**Jellyfin version**
10.7.0

**Describe the bug**
Wrong text displayed in menus: json parser is picking up wrong values for AlbumArtists, Series and probably other fields. Seems to prefer grabbing Backdrop or blurhash fingerprints for some reason, but it's probably a coincidence.

I hope to get a fix in before the weekend. Entries selected should still work as far as I've gathered, they just have garbled names.

UPDATE: this bug is nasty, or at least I'm having a hard time wrapping my head around it. Also not finding a lot of time to dedicate to it. It'll take a while to fix :(

**Comment by fullmetal1** [comment]
Will there be a new release once this issue is fixed?

**Comment by Aanok** [comment]
@fullmetal1 Yes, definitely. I hope to make use of holiday time and get everything sorted out by Easter Monday :)
