### ISSUE TITLE
jftui fails to play anything

### ISSUE THREAD

**Issue by FunctionalHacker** [Aanok/jftui#2]
I get `Error: jf_menu_play_item video types not yet supported.` when I try to play anything. I don't know of a way to get debug output, so please ask if you need anything more from me.

EDIT: It seems I'm able to play music. Does the output mean that video playback is not yet supported?

**Comment by Aanok** [comment]
Correct! That's still a WIP unfortunately. I plan to get on it for 0.2 :)

**Comment by FunctionalHacker** [comment]
Cool! If you're wondering what all of the traffic has been about today, I made a post on [r/jellyfin](https://reddit.com/r/jellyfin)  to get some exposure on your software :smile:

**Comment by Aanok** [comment]
Oh, I was wondering in fact, there was quite the bump. Thanks!

**Comment by FunctionalHacker** [comment]
:v: I'll see if I can put some time aside to make some improvements but that's a big if since I'm quite busy at school.
