### ISSUE TITLE
libmpv2 warning is unnecessary

### ISSUE THREAD

**Issue by hstejas** [Aanok/jftui#24]
I have been using jftui with libmpv2 (2.0) for a few days now without any issues. (on opensuse tumbleweed)

But I saw this warning so wanted to mention that it is working with 2.0
> Warning: found libmpv version 2.0, but jftui expects 1.xx. mpv will probably not work.

**Comment by Aanok** [comment]
Version 2? Good grief, what's next, version 3? Give me a break! :weary: 

Jokes aside, thanks for the notice. I've reviewed the libmpv changelog and indeed the breaking changes won't impact jftui. The warning will be fixed :+1:
