### ISSUE TITLE
jftui using default mpv keybindings

### ISSUE THREAD

**Issue by WnndGws** [Aanok/jftui#26]
**jftui version**
jftui 0.5.1, libmpv 1.109, libcurl 7.83.1 OpenSSL/1.1.1o, yajl 20100

**Describe the bug**
When opening media through jftui, it uses a MPV player that uses all the default keybindings rather than what i have in ~/.config/mpv/input.conf like expected. All settings work when opening video normally through cli. If this is a setting on my side I cant find it. Any help would be great!

**To Reproduce**
Play any media file, try to use custom keybinding

**Expected behavior**
The MPV to use my keybindings

**Comment by Aanok** [comment]
Hey there! jftui looks for mpv configs in ~/.config/jftui, not in ~/.config/mpv. To quote from the readme:

> jftui will drop into a command line instance of mpv when starting playback. It will use mpv.conf and input.conf files found in $XDG_CONFIG_HOME/jftui (this location can be overridden with the --config-dir argument). It will also try and load scripts found in the same folder, but no guarantees are made about them actually working correctly.

I personally just put a symlink in jftui's folder :)

Feel free to close the issue if this solves your problem or let me know otherwise.

**Comment by WnndGws** [comment]
Thanks so much. I must have missed that. I spent forever on the wiki etc.
Guess the brain reads what it wants to!
