### ISSUE TITLE
Login broken on 10.8.0

### ISSUE THREAD

**Issue by fullmetal1** [Aanok/jftui#27]
**jftui version**
jftui 0.5.1, libmpv 1.109, libcurl 7.83.1 OpenSSL/1.1.1o, yajl 20100

**Describe the bug**
Attempting to log into the server with ```jellyfin --login``` prompts the username and password as usual, but when correct credentials are entered, jftui prints `FATAL: could not login: Error processing request..`

**To Reproduce**
install or upgrade jellyfin to 10.8.0 and attempt to log in.

**Expected behavior**
Login should proceed without issue

**SIGSEGV backtracke**
N/A

**Comment by Aanok** [comment]
A header in the login request became case-sensitive with 10.8.0, causing the error. Thanks for the report!
