### ISSUE TITLE
Allow user to set player path

### ISSUE THREAD

**Issue by WnndGws** [Aanok/jftui#29]
**jftui version**
jftui 0.6.0, libmpv 1.109, libcurl 7.85.0 OpenSSL/1.1.1q, yajl 20100

**Describe the feature request**
If we could select the path to mpv it might allow for syncplay to work

**Comment by Aanok** [comment]
Good idea!

**Comment by Aanok** [comment]
Sorry, I don't know why I said this was a good idea. It's not possible, because jftui doesn't wrap an mpv process but embeds an mpv core internally via libmpv.

Can't do : (
