### ISSUE TITLE
Video title not set correctly in mpv

### ISSUE THREAD

**Issue by FunctionalHacker** [Aanok/jftui#3]
I'm glad to see you got video playback working!

I found one issue which is (possibly) an easy fix. The video title, the one in OSD right above the seek bar, is set as `file;` instead of the real title. 

From my testing, at least on standalone mpv, you can force the video title with `--force-media-title="My awesome title"`. I could not find any documentation on libmpv on how to do this.

**Comment by Aanok** [comment]
Good point, I'll look into it.
