### ISSUE TITLE
Allow mpv config dir to be set separately

### ISSUE THREAD

**Issue by ammgws** [Aanok/jftui#30]
`jftui 0.6.0, libmpv 1.109, libcurl 7.85.0 OpenSSL/1.1.1q, yajl 20100`

jftui uses `mpv.conf` and `input.conf` files found in `$XDG_CONFIG_HOME/jftui`, so I am symlinking my mpv config from `~/.config/mpv` into the jftui config directory because I want to use the same config. I initially tried the `--config-dir` argument but this overrides the config dir for the jftui `settings` file itself as well.

Would it be reasonable to have a separate command `--mpv-config-dir` that only overrides the config dir path that jftui passes to mpv here: https://github.com/Aanok/jftui/blob/9c4e88ee182c2bff7100fc2f7af26e74e0e6f0a4/src/menu.c#L725 ?

If so I can work on it and submit a PR.

**Comment by Aanok** [comment]
It's not necessarily unreasonable, but I personally solve this problem symlinking mpv.conf and input.conf individually in jftui's config folder. Is there some specific reason you're unwilling to do that? "Two symlinks are more of a hassle than one symlink" is a valid reason :D

**Comment by Aanok** [comment]
Considering the lack of followup and the presence of a very easy way to do this already, I'm closing as a won't do.
