### ISSUE TITLE
[Question] Are scripts in `/usr/share/mpv/scripts` and `/etc/mpv/scripts` ignored?

### ISSUE THREAD

**Issue by onemoresuza** [Aanok/jftui#37]
# Description

The README states:

> jftui will drop into a command line instance of mpv when starting playback. It will use `mpv.conf`
> and `input.conf` files found in `$XDG_CONFIG_HOME/jftui` (this location can be overridden with
> the `--config-dir` argument). **It will also try and load scripts found in the same folder, but no
> guarantees are made about them actually working correctly**.

Does this mean that **only** scripts within that folder are loaded?

# Use Case

Some plugins can be installed through the system's package manager, *e.g.*, [mpv-mpris][mpv-mpris], which puts them in either `/etc/mpv/scripts` or `/usr/share/mpv/scripts`.

[mpv-mpris]: <https://archlinux.org/packages/extra/x86_64/mpv-mpris/> "Arch Linux package for mpv-mpris"

**Comment by Aanok** [comment]
Yes, the only configuration loaded is from the jftui-specific folder, including scripts and plugins. Unfortunately libmpv doesn't offer a simple way to cascade settings from system to user scopes like mpv does and you have to choose one single folder.

But nothing stops you from symlinking /etc/mpv/scripts : )
