### ISSUE TITLE
Each new page navigation opens a new mpv instance

### ISSUE THREAD

**Issue by fullmetal1** [Aanok/jftui#40]
**jftui version**
jftui 0.7.0, libmpv 2.1, libcurl 8.2.1 OpenSSL/3.1.2, yajl 20100

**Describe the bug**
After the program loads the main view of the server it connects to, navigating to TV shows will open an instance of mpv with no file (my mpv requests that I Drop files or URLs into the window to start playing anything). This behaviour will repeat with each new page navigated to (cycling back and forth will open additional mpv instances as well). the `q` hotkey on mpv does not close the instance. Like normal jftui mpv instances, no additional processes appear in the process list.

**To Reproduce**
Open jftui, navigate through your server's pages, minimizing mpv as necessary to reproduce further

**Expected behavior**
At first I suspected that this might be some abberant iteration of the 'open mpv with jftui' feature request, but I don't see that in the commit log or anywhere else, so I suspect that the expected behaviour is for no mpv instances to open, as they were in the second most recent version.

**SIGSEGV backtrace**
N/A

**Comment by Aanok** [comment]
Nice catch! It was a regression from some code refactoring.
