### ISSUE TITLE
add cli mode

### ISSUE THREAD

**Issue by timrosu** [Aanok/jftui#43]
I figured it would be a good idea to have jellyfin cli client. I want to make it work with rofi or dmenu.
It would would have similar text layout as now, but would just return text when specific argument is passed, instead of waiting for input. Search could be handled externally.

**Comment by Aanok** [comment]
Hi! This is currently outside the scope of the project as I see it. However, the codebase is open sourced under the most permissive license I could find, so you're absolutely encouraged to fork it and get some work done. If you do, please make sure to let me know! I'd love to have a look : )
